USE [RefData]
GO

INSERT INTO Countries(Name, Abbreviation) VALUES ('Afghanistan','AFG');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Åland Islands','ALA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Albania','ALB');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Algeria','DZA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('American Samoa','ASM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Andorra','AND');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Angola','AGO');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Anguilla','AIA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Antarctica','ATA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Antigua and Barbuda','ATG');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Argentina','ARG');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Armenia','ARM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Aruba','ABW');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Australia','AUS');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Austria','AUT');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Azerbaijan','AZE');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Bahamas','BHS');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Bahrain','BHR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Bangladesh','BGD');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Barbados','BRB');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Belarus','BLR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Belgium','BEL');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Belize','BLZ');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Benin','BEN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Bermuda','BMU');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Bhutan','BTN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Bolivia','BOL');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Bonaire, Saint Eustatius and Saba','BES');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Bosnia and Herzegovina','BIH');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Botswana','BWA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Bouvet Island','BVT');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Brazil','BRA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('British Indian Ocean Territory','IOT');
INSERT INTO Countries(Name, Abbreviation) VALUES ('British Virgin Islands','VGB');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Brunei','BRN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Bulgaria','BGR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Burkina Faso','BFA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Burma','MMR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Burundi','BDI');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Cambodia','KHM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Cameroon','CMR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Canada','CAN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Cape Verde','CPV');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Cayman Islands','CYM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Central African Republic','CAF');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Chad','TCD');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Chile','CHL');
INSERT INTO Countries(Name, Abbreviation) VALUES ('China','CHN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Christmas Island','CXR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Cocos (Keeling) Islands','CCK');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Colombia','COL');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Comoros','COM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Cook Islands','COK');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Costa Rica','CRI');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Croatia','HRV');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Cuba','CUB');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Curacao','CUW');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Cyprus','CYP');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Czechia','CZE');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Democratic Republic of the Congo','COD');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Denmark','DNK');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Djibouti','DJI');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Dominica','DMA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Dominican Republic','DOM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('East Timor','TLS');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Ecuador','ECU');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Egypt','EGY');
INSERT INTO Countries(Name, Abbreviation) VALUES ('El Salvador','SLV');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Equatorial Guinea','GNQ');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Eritrea','ERI');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Estonia','EST');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Eswatini','SWZ');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Ethiopia','ETH');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Falkland Islands','FLK');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Faroe Islands','FRO');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Federated States of Micronesia','FSM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Fiji','FJI');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Finland','FIN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('France','FRA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('French Guiana','GUF');
INSERT INTO Countries(Name, Abbreviation) VALUES ('French Polynesia','PYF');
INSERT INTO Countries(Name, Abbreviation) VALUES ('French Southern and Antarctic Lands','ATF');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Gabon','GAB');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Gambia','GMB');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Georgia','GEO');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Germany','DEU');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Ghana','GHA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Gibraltar','GIB');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Greece','GRC');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Greenland','GRL');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Grenada','GRD');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Guadeloupe','GLP');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Guam','GUM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Guatemala','GTM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Guernsey','GGY');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Guinea','GIN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Guinea-Bissau','GNB');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Guyana','GUY');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Haiti','HTI');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Heard Island and McDonald Islands','HMD');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Honduras','HND');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Hong Kong','HKG');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Hungary','HUN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Iceland','ISL');
INSERT INTO Countries(Name, Abbreviation) VALUES ('India','IND');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Indonesia','IDN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Iran','IRN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Iraq','IRQ');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Ireland','IRL');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Isle of Man','IMN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Israel','ISR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Italy','ITA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Ivory Coast','CIV');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Jamaica','JAM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Japan','JPN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Jersey','JEY');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Jordan','JOR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Kazakhstan','KAZ');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Kenya','KEN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Kiribati','KIR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Kosovo','XKX');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Kuwait','KWT');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Kyrgyzstan','KGZ');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Laos','LAO');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Latvia','LVA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Lebanon','LBN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Lesotho','LSO');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Liberia','LBR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Libya','LBY');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Liechtenstein','LIE');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Lithuania','LTU');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Luxembourg','LUX');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Macao','MAC');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Madagascar','MDG');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Malawi','MWI');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Malaysia','MYS');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Maldives','MDV');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Mali','MLI');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Malta','MLT');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Marshall Islands','MHL');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Martinique','MTQ');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Mauritania','MRT');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Mauritius','MUS');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Mayotte','MYT');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Mexico','MEX');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Moldova','MDA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Mongolia','MNG');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Montenegro','MNE');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Montserrat','MSR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Morocco','MAR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Mozambique','MOZ');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Namibia','NAM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Nauru','NRU');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Nepal','NPL');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Netherlands','NLD');
INSERT INTO Countries(Name, Abbreviation) VALUES ('New Caledonia','NCL');
INSERT INTO Countries(Name, Abbreviation) VALUES ('New Zealand','NZL');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Nicaragua','NIC');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Niger','NER');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Nigeria','NGA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Niue','NIU');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Norfolk Island','NFK');
INSERT INTO Countries(Name, Abbreviation) VALUES ('North Korea','PRK');
INSERT INTO Countries(Name, Abbreviation) VALUES ('North Macedonia','MKD');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Northern Mariana Islands','MNP');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Norway','NOR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Oman','OMN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Pakistan','PAK');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Palau','PLW');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Palestine','PSE');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Panama','PAN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Papua New Guinea','PNG');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Paraguay','PRY');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Peru','PER');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Philippines','PHL');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Pitcairn Islands','PCN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Poland','POL');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Portugal','PRT');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Principality of Monaco','MCO');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Puerto Rico','PRI');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Qatar','QAT');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Republic of the Congo','COG');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Reunion','REU');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Romania','ROU');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Russia','RUS');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Rwanda','RWA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Saint Barthelemy','BLM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Saint Helena, Ascension and Tristan da Cunha','SHN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Saint Kitts and Nevis','KNA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Saint Lucia','LCA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Saint Martin','MAF');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Saint Pierre and Miquelon','SPM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Saint Vincent and the Grenadines','VCT');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Samoa','WSM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('San Marino','SMR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Sao Tome and Principe','STP');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Saudi Arabia','SAU');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Senegal','SEN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Serbia','SRB');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Seychelles','SYC');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Sierra Leone','SLE');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Singapore','SGP');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Sint Maarten','SXM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Slovakia','SVK');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Slovenia','SVN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Solomon Islands','SLB');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Somalia','SOM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('South Africa','ZAF');
INSERT INTO Countries(Name, Abbreviation) VALUES ('South Georgia and South Sandwich Islands','SGS');
INSERT INTO Countries(Name, Abbreviation) VALUES ('South Korea','KOR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('South Sudan','SSD');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Spain','ESP');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Sri Lanka','LKA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Sudan','SDN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Suriname','SUR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Svalbard','SJM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Sweden','SWE');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Switzerland','CHE');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Syria','SYR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Taiwan','TWN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Tajikistan','TJK');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Tanzania','TZA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Thailand','THA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Togo','TGO');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Tokelau','TKL');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Tonga','TON');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Trinidad and Tobago','TTO');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Tunisia','TUN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Turkey','TUR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Turkmenistan','TKM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Turks and Caicos Islands','TCA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Tuvalu','TUV');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Uganda','UGA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Ukraine','UKR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('United Arab Emirates','ARE');
INSERT INTO Countries(Name, Abbreviation) VALUES ('United Kingdom','GBR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('United States','USA');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Uruguay','URY');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Uzbekistan','UZB');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Vanuatu','VUT');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Vatican City','VAT');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Venezuela','VEN');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Vietnam','VNM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Virgin Islands','VIR');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Wallis and Futuna','WLF');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Western Sahara','ESH');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Yemen','YEM');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Zambia','ZMB');
INSERT INTO Countries(Name, Abbreviation) VALUES ('Zimbabwe','ZWE');
