USE [RefData]
GO

INSERT INTO States(Name, Abbreviation) VALUES ('Alabama','AL');
INSERT INTO States(Name, Abbreviation) VALUES ('Alaska','AK');
INSERT INTO States(Name, Abbreviation) VALUES ('Arizona','AZ');
INSERT INTO States(Name, Abbreviation) VALUES ('Arkansas','AR');
INSERT INTO States(Name, Abbreviation) VALUES ('California','CA');
INSERT INTO States(Name, Abbreviation) VALUES ('Colorado','CO');
INSERT INTO States(Name, Abbreviation) VALUES ('Connecticut','CT');
INSERT INTO States(Name, Abbreviation) VALUES ('Delaware','DE');
INSERT INTO States(Name, Abbreviation) VALUES ('District of Columbia','DC');
INSERT INTO States(Name, Abbreviation) VALUES ('Florida','FL');
INSERT INTO States(Name, Abbreviation) VALUES ('Georgia','GA');
INSERT INTO States(Name, Abbreviation) VALUES ('Hawaii','HI');
INSERT INTO States(Name, Abbreviation) VALUES ('Idaho','ID');
INSERT INTO States(Name, Abbreviation) VALUES ('Illinois','IL');
INSERT INTO States(Name, Abbreviation) VALUES ('Indiana','IN');
INSERT INTO States(Name, Abbreviation) VALUES ('Iowa','IA');
INSERT INTO States(Name, Abbreviation) VALUES ('Kansas','KS');
INSERT INTO States(Name, Abbreviation) VALUES ('Kentucky','KY');
INSERT INTO States(Name, Abbreviation) VALUES ('Louisiana','LA');
INSERT INTO States(Name, Abbreviation) VALUES ('Maine','ME');
INSERT INTO States(Name, Abbreviation) VALUES ('Maryland','MD');
INSERT INTO States(Name, Abbreviation) VALUES ('Massachusetts','MA');
INSERT INTO States(Name, Abbreviation) VALUES ('Michigan','MI');
INSERT INTO States(Name, Abbreviation) VALUES ('Minnesota','MN');
INSERT INTO States(Name, Abbreviation) VALUES ('Mississippi','MS');
INSERT INTO States(Name, Abbreviation) VALUES ('Missouri','MO');
INSERT INTO States(Name, Abbreviation) VALUES ('Montana','MT');
INSERT INTO States(Name, Abbreviation) VALUES ('Nebraska','NE');
INSERT INTO States(Name, Abbreviation) VALUES ('Nevada','NV');
INSERT INTO States(Name, Abbreviation) VALUES ('New Hampshire','NH');
INSERT INTO States(Name, Abbreviation) VALUES ('New Jersey','NJ');
INSERT INTO States(Name, Abbreviation) VALUES ('New Mexico','NM');
INSERT INTO States(Name, Abbreviation) VALUES ('New York','NY');
INSERT INTO States(Name, Abbreviation) VALUES ('North Carolina','NC');
INSERT INTO States(Name, Abbreviation) VALUES ('North Dakota','ND');
INSERT INTO States(Name, Abbreviation) VALUES ('Ohio','OH');
INSERT INTO States(Name, Abbreviation) VALUES ('Oklahoma','OK');
INSERT INTO States(Name, Abbreviation) VALUES ('Oregon','OR');
INSERT INTO States(Name, Abbreviation) VALUES ('Pennsylvania','PA');
INSERT INTO States(Name, Abbreviation) VALUES ('Rhode Island','RI');
INSERT INTO States(Name, Abbreviation) VALUES ('South Carolina','SC');
INSERT INTO States(Name, Abbreviation) VALUES ('South Dakota','SD');
INSERT INTO States(Name, Abbreviation) VALUES ('Tennessee','TN');
INSERT INTO States(Name, Abbreviation) VALUES ('Texas','TX');
INSERT INTO States(Name, Abbreviation) VALUES ('Utah','UT');
INSERT INTO States(Name, Abbreviation) VALUES ('Vermont','VT');
INSERT INTO States(Name, Abbreviation) VALUES ('Virginia','VA');
INSERT INTO States(Name, Abbreviation) VALUES ('Washington','WA');
INSERT INTO States(Name, Abbreviation) VALUES ('West Virginia','WV');
INSERT INTO States(Name, Abbreviation) VALUES ('Wisconsin','WI');
INSERT INTO States(Name, Abbreviation) VALUES ('Wyoming','WY');